"""
Seed script -> populates the jobs table with realistic SWE roles.
Each job gets an auto-generated embedding via OpenRouter.

Usage: python -m scripts.seed_jobs
Run from the backend/ directory with the venv activated.
"""

import asyncio
import sys
import os

# -> add backend dir to path so we can import app modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.services.job_service import create_job

JOBS = [
    {
        "title": "Senior Backend Engineer",
        "company": "Razorpay",
        "description": "Build and scale payment infrastructure serving millions of businesses. You will design APIs, work on distributed systems, and optimize high-throughput transaction pipelines. The role involves working closely with product and infrastructure teams to ship reliable financial services.",
        "requirements": "5+ years backend experience. Strong understanding of distributed systems, message queues, and database internals. Experience with microservices architecture and API design.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 5,
        "experience_max": 10,
        "tech_stack": ["Go", "Python", "PostgreSQL", "Redis", "Kafka", "Kubernetes"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 3000000,
        "salary_max": 5500000,
        "salary_currency": "INR",
        "apply_url": "https://razorpay.com/careers",
        "source": "manual",
    },
    {
        "title": "Frontend Developer",
        "company": "Swiggy",
        "description": "Work on the consumer-facing web app used by millions for food delivery. You will build responsive, performant interfaces, optimize Core Web Vitals, and collaborate with designers to create seamless ordering experiences.",
        "requirements": "3+ years frontend experience with React. Familiarity with state management, performance profiling, and component-driven architecture.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2000000,
        "salary_max": 4000000,
        "salary_currency": "INR",
        "apply_url": "https://swiggy.com/careers",
        "source": "manual",
    },
    {
        "title": "React Engineer",
        "company": "Zerodha",
        "description": "Build and maintain trading dashboards used by millions of retail investors. Create real-time data visualization components, optimize rendering for high-frequency data updates, and ensure accessibility across the platform.",
        "requirements": "3+ years React experience. Understanding of WebSocket-based real-time data, charting libraries, and performance optimization for data-heavy UIs.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["React", "JavaScript", "D3.js", "WebSocket", "CSS"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 2500000,
        "salary_max": 4500000,
        "salary_currency": "INR",
        "apply_url": "https://zerodha.com/careers",
        "source": "manual",
    },
    {
        "title": "Full Stack Developer",
        "company": "Freshworks",
        "description": "Work across the stack on CRM and customer engagement products. Build features end to end from database schema design to API implementation to frontend components. Participate in architecture discussions and code reviews.",
        "requirements": "3+ years full stack experience. Comfortable with both backend services and frontend frameworks. Understanding of REST APIs, relational databases, and modern frontend tooling.",
        "employment_type": "full_time",
        "role_type": "fullstack",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["Ruby on Rails", "React", "PostgreSQL", "Redis", "AWS"],
        "location": "Chennai",
        "is_remote": False,
        "salary_min": 1800000,
        "salary_max": 3500000,
        "salary_currency": "INR",
        "apply_url": "https://freshworks.com/careers",
        "source": "manual",
    },
    {
        "title": "AIML Software Engineer",
        "company": "Google",
        "description": "Design and implement machine learning models for Google Search quality. Work on large-scale data pipelines, model training infrastructure, and experiment tracking. Collaborate with research scientists to bring prototypes to production.",
        "requirements": "4+ years ML engineering experience. Strong Python and ML framework skills. Experience with large-scale distributed training, model serving, and MLOps practices.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["Python", "TensorFlow", "JAX", "Kubernetes", "BigQuery", "C++"],
        "location": "Hyderabad",
        "is_remote": False,
        "salary_min": 4000000,
        "salary_max": 8000000,
        "salary_currency": "INR",
        "apply_url": "https://careers.google.com",
        "source": "manual",
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Flipkart",
        "description": "Build recommendation systems and search ranking models for one of India's largest e-commerce platforms. Design feature stores, build training pipelines, and deploy models that directly impact user experience and business metrics.",
        "requirements": "3+ years ML engineering experience. Strong Python skills, experience with recommendation systems or NLP. Familiarity with Spark, Airflow, or similar data engineering tools.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "PyTorch", "Spark", "Airflow", "Elasticsearch", "AWS"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 3000000,
        "salary_max": 6000000,
        "salary_currency": "INR",
        "apply_url": "https://flipkart.com/careers",
        "source": "manual",
    },
    {
        "title": "DevOps Engineer",
        "company": "PhonePe",
        "description": "Manage and scale infrastructure for a high-traffic payments platform. Build CI/CD pipelines, manage Kubernetes clusters, implement observability stacks, and automate infrastructure provisioning. Ensure 99.99% uptime for critical payment services.",
        "requirements": "4+ years DevOps experience. Strong Linux, networking, and cloud infrastructure skills. Hands-on with container orchestration and infrastructure as code.",
        "employment_type": "full_time",
        "role_type": "devops",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["Kubernetes", "Docker", "Terraform", "AWS", "Prometheus", "Grafana", "Jenkins"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://phonepe.com/careers",
        "source": "manual",
    },
    {
        "title": "Cloud Infrastructure Engineer",
        "company": "Atlassian",
        "description": "Design and maintain cloud infrastructure for Jira and Confluence. Work on multi-region deployments, automated scaling, cost optimization, and disaster recovery. Build internal tooling for engineering productivity.",
        "requirements": "5+ years cloud infrastructure experience. Deep AWS or GCP expertise. Strong scripting skills and experience with infrastructure as code.",
        "employment_type": "full_time",
        "role_type": "devops",
        "experience_min": 5,
        "experience_max": 10,
        "tech_stack": ["AWS", "Terraform", "Python", "Kubernetes", "Datadog", "Go"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 3500000,
        "salary_max": 7000000,
        "salary_currency": "INR",
        "apply_url": "https://atlassian.com/careers",
        "source": "manual",
    },
    {
        "title": "Software Development Engineer II",
        "company": "Amazon",
        "description": "Build customer-facing features for Amazon's retail platform. Own end-to-end delivery of features from design through deployment. Work in a fast-paced environment with high standards for code quality, testing, and operational excellence.",
        "requirements": "3+ years software development experience. Strong CS fundamentals including data structures and algorithms. Experience with large-scale distributed systems.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Java", "AWS", "DynamoDB", "Spring Boot", "Microservices"],
        "location": "Hyderabad",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://amazon.jobs",
        "source": "manual",
    },
    {
        "title": "UI Developer",
        "company": "Notion",
        "description": "Create polished, accessible UI components for Notion's editor and workspace features. Work on complex interaction patterns, drag-and-drop, rich text editing, and collaborative real-time features. Focus on craft and user delight.",
        "requirements": "4+ years frontend experience. Deep CSS and DOM knowledge. Experience building complex interactive components. Eye for design and attention to micro-interactions.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["React", "TypeScript", "CSS", "WebSocket", "Prosemirror"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 5000000,
        "salary_max": 10000000,
        "salary_currency": "INR",
        "apply_url": "https://notion.so/careers",
        "source": "manual",
    },
    {
        "title": "Backend Developer - Golang",
        "company": "Dream11",
        "description": "Build high-concurrency backend systems for fantasy sports. Handle millions of concurrent users during live matches. Design real-time scoring engines, leaderboard systems, and contest management APIs.",
        "requirements": "3+ years backend experience, preferably with Go. Understanding of concurrency patterns, caching strategies, and real-time data processing.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["Go", "Redis", "MongoDB", "Kafka", "gRPC", "Docker"],
        "location": "Mumbai",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://dream11.com/careers",
        "source": "manual",
    },
    {
        "title": "Python Backend Developer",
        "company": "Postman",
        "description": "Build APIs and backend services for Postman's collaboration platform. Work on workspace management, API monitoring, and integration features. Write clean, well-tested Python code and participate in architecture decisions.",
        "requirements": "2+ years Python backend experience. Familiarity with FastAPI or Django. Understanding of RESTful API design and database modeling.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "AWS"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 1800000,
        "salary_max": 3500000,
        "salary_currency": "INR",
        "apply_url": "https://postman.com/careers",
        "source": "manual",
    },
    {
        "title": "Data Engineer",
        "company": "Ola",
        "description": "Build and maintain data pipelines that process terabytes of ride data daily. Design data warehouse schemas, build ETL workflows, and enable analytics teams with clean, reliable data. Work with real-time streaming for surge pricing and demand prediction.",
        "requirements": "3+ years data engineering experience. Strong SQL skills, experience with distributed processing frameworks, and familiarity with cloud data warehouses.",
        "employment_type": "full_time",
        "role_type": "data",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "Spark", "Airflow", "Kafka", "BigQuery", "dbt"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2000000,
        "salary_max": 4500000,
        "salary_currency": "INR",
        "apply_url": "https://ola.com/careers",
        "source": "manual",
    },
    {
        "title": "Mobile Developer - React Native",
        "company": "CRED",
        "description": "Build premium mobile experiences for credit card management and payments. Work on smooth animations, complex gestures, and offline-first architecture. Collaborate with design to create award-winning UI patterns.",
        "requirements": "3+ years React Native experience. Strong JavaScript fundamentals, understanding of native module bridging, and experience with performance optimization on mobile.",
        "employment_type": "full_time",
        "role_type": "mobile",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["React Native", "TypeScript", "Redux", "Native Modules", "Firebase"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://cred.club/careers",
        "source": "manual",
    },
    {
        "title": "Freelance Web Developer",
        "company": "Toptal",
        "description": "Join Toptal's network of freelance developers. Work on projects for Fortune 500 companies and startups. Choose your own hours and projects. Build web applications, e-commerce platforms, and SaaS products for diverse clients.",
        "requirements": "3+ years professional web development. Strong portfolio with real-world projects. Ability to work independently, communicate clearly, and deliver on deadlines.",
        "employment_type": "freelance",
        "role_type": "fullstack",
        "experience_min": 3,
        "experience_max": 15,
        "tech_stack": ["React", "Node.js", "Python", "PostgreSQL", "AWS"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 3000000,
        "salary_max": 8000000,
        "salary_currency": "INR",
        "apply_url": "https://toptal.com/developers",
        "source": "manual",
    },
    {
        "title": "Contract Software Engineer",
        "company": "Accenture",
        "description": "Join a 6-month engagement building an internal CRM platform for a financial services client. You will design and implement REST APIs, build frontend components, and work with the client's data team on integrations.",
        "requirements": "2+ years software engineering experience. Comfortable with both frontend and backend. Ability to ramp up quickly on unfamiliar codebases.",
        "employment_type": "contract",
        "role_type": "fullstack",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Java", "Angular", "Oracle DB", "Spring Boot"],
        "location": "Mumbai",
        "is_remote": False,
        "salary_min": 100000,
        "salary_max": 200000,
        "salary_currency": "INR",
        "apply_url": "https://accenture.com/careers",
        "source": "manual",
    },
    {
        "title": "Government IT Officer - NIC",
        "company": "National Informatics Centre",
        "description": "Develop and maintain e-governance applications for central government departments. Work on citizen-facing portals, internal workflow systems, and data management tools. Participate in the Digital India initiative.",
        "requirements": "B.Tech/MCA with valid GATE score or equivalent. Familiarity with web technologies and database management. Understanding of government IT standards and security protocols.",
        "employment_type": "government",
        "role_type": "fullstack",
        "experience_min": 0,
        "experience_max": 3,
        "tech_stack": ["Java", "Spring", "PostgreSQL", "HTML", "CSS", "JavaScript"],
        "location": "New Delhi",
        "is_remote": False,
        "salary_min": 800000,
        "salary_max": 1200000,
        "salary_currency": "INR",
        "apply_url": "https://nic.in/careers",
        "source": "manual",
    },
    {
        "title": "SDE Intern",
        "company": "Microsoft",
        "description": "Join Microsoft as a software engineering intern. Work on real product features in Teams, Azure, or Office. Get mentorship from senior engineers, participate in design reviews, and ship code used by millions.",
        "requirements": "Currently pursuing B.Tech/M.Tech in CS or related field. Strong problem-solving skills and familiarity with at least one programming language. Prior project experience is a plus.",
        "employment_type": "internship",
        "role_type": "fullstack",
        "experience_min": 0,
        "experience_max": 0,
        "tech_stack": ["C#", "TypeScript", "React", "Azure", ".NET"],
        "location": "Hyderabad",
        "is_remote": False,
        "salary_min": 80000,
        "salary_max": 150000,
        "salary_currency": "INR",
        "apply_url": "https://careers.microsoft.com",
        "source": "manual",
    },
    {
        "title": "Security Engineer",
        "company": "Flipkart",
        "description": "Protect Flipkart's platform and customer data. Conduct security assessments, build automated vulnerability scanning tools, and design secure architecture patterns. Respond to security incidents and work with engineering teams to fix vulnerabilities.",
        "requirements": "3+ years application security experience. Understanding of OWASP Top 10, penetration testing, and secure code review. Experience with security automation and CI/CD integration.",
        "employment_type": "full_time",
        "role_type": "security",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "Burp Suite", "AWS Security", "Docker", "Kubernetes", "SAST/DAST"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://flipkart.com/careers",
        "source": "manual",
    },
    {
        "title": "Site Reliability Engineer",
        "company": "Zomato",
        "description": "Keep Zomato's food delivery platform running at scale. Build observability tooling, manage incident response, automate failure recovery, and work on capacity planning. Balance reliability with shipping velocity.",
        "requirements": "3+ years SRE or DevOps experience. Strong Linux and networking fundamentals. Experience with monitoring, alerting, and on-call rotations. Programming ability in Python or Go.",
        "employment_type": "full_time",
        "role_type": "devops",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "Go", "Kubernetes", "Prometheus", "Terraform", "AWS"],
        "location": "Gurgaon",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://zomato.com/careers",
        "source": "manual",
    },
    {
        "title": "Blockchain Developer",
        "company": "Polygon",
        "description": "Build and optimize Layer 2 scaling solutions for Ethereum. Work on consensus mechanisms, bridge contracts, and developer tooling. Contribute to open-source blockchain infrastructure used by thousands of dApps.",
        "requirements": "2+ years blockchain development experience. Strong understanding of Ethereum, Solidity, and EVM internals. Experience with Rust or Go is a plus.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 2,
        "experience_max": 6,
        "tech_stack": ["Solidity", "Go", "Rust", "Ethereum", "Web3.js"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 4000000,
        "salary_max": 9000000,
        "salary_currency": "INR",
        "apply_url": "https://polygon.technology/careers",
        "source": "manual",
    },
    {
        "title": "QA Automation Engineer",
        "company": "BrowserStack",
        "description": "Build automated testing frameworks for BrowserStack's cross-browser testing platform. Design test strategies, create end-to-end test suites, and improve testing infrastructure. Help ship reliable software faster.",
        "requirements": "2+ years QA automation experience. Proficiency with Selenium, Cypress, or Playwright. Understanding of CI/CD and test pyramid principles.",
        "employment_type": "full_time",
        "role_type": "qa",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Selenium", "Cypress", "Python", "JavaScript", "Jenkins", "Docker"],
        "location": "Mumbai",
        "is_remote": True,
        "salary_min": 1500000,
        "salary_max": 3000000,
        "salary_currency": "INR",
        "apply_url": "https://browserstack.com/careers",
        "source": "manual",
    },
    {
        "title": "Product Engineer",
        "company": "Razorpay",
        "description": "Own features end-to-end in Razorpay's payment products. Work across the stack to build merchant-facing tools, payment flows, and dashboard features. Think like a product owner and code like an engineer.",
        "requirements": "2+ years product engineering experience. Full stack capability with strong frontend skills. Ability to understand business context and translate it into technical solutions.",
        "employment_type": "full_time",
        "role_type": "fullstack",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["React", "Node.js", "Go", "PostgreSQL", "Redis"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2000000,
        "salary_max": 4000000,
        "salary_currency": "INR",
        "apply_url": "https://razorpay.com/careers",
        "source": "manual",
    },
    {
        "title": "NLP Research Engineer",
        "company": "ShareChat",
        "description": "Build NLP models for content understanding across Indian languages. Work on text classification, sentiment analysis, and content moderation at scale. Bridge the gap between research and production ML systems.",
        "requirements": "3+ years NLP experience. Strong Python and deep learning skills. Experience with transformer models, multilingual NLP, and deploying models at scale.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "PyTorch", "Hugging Face", "FastAPI", "Docker", "AWS"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5500000,
        "salary_currency": "INR",
        "apply_url": "https://sharechat.com/careers",
        "source": "manual",
    },
]


async def seed():
    print(f"Seeding {len(JOBS)} jobs...")
    for i, job in enumerate(JOBS):
        try:
            result = await create_job(job)
            print(f"  [{i+1}/{len(JOBS)}] Created: {job['title']} at {job['company']}")
        except Exception as e:
            print(f"  [{i+1}/{len(JOBS)}] FAILED: {job['title']} -> {e}")

    print("Done!")


if __name__ == "__main__":
    asyncio.run(seed())
