"""
Seed script -> adds more jobs to the database.
Usage: python -m scripts.seed_jobs_v2
Run from the backend/ directory with the venv activated.
"""

import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.services.job_service import create_job

JOBS = [
    {
        "title": "Staff Frontend Engineer",
        "company": "Stripe",
        "description": "Lead frontend architecture for Stripe's payment dashboard. Define technical direction, mentor engineers, and build complex financial UIs that handle real-time data at scale. Drive adoption of modern patterns across the frontend org.",
        "requirements": "8+ years frontend experience. Track record of leading large frontend projects. Deep expertise in React, performance optimization, and design systems.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 8,
        "experience_max": 14,
        "tech_stack": ["React", "TypeScript", "GraphQL", "Next.js", "Storybook"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 8000000,
        "salary_max": 15000000,
        "salary_currency": "INR",
        "apply_url": "https://stripe.com/jobs",
        "source": "manual",
    },
    {
        "title": "Backend Engineer - Payments",
        "company": "Paytm",
        "description": "Build payment processing systems handling millions of daily transactions. Design fault-tolerant services, implement payment gateway integrations, and ensure PCI-DSS compliance across the stack.",
        "requirements": "3+ years backend experience in fintech or payments. Understanding of payment protocols, idempotency, and distributed transactions.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["Java", "Spring Boot", "MySQL", "Redis", "Kafka", "Docker"],
        "location": "Noida",
        "is_remote": False,
        "salary_min": 2000000,
        "salary_max": 4000000,
        "salary_currency": "INR",
        "apply_url": "https://paytm.com/careers",
        "source": "manual",
    },
    {
        "title": "Platform Engineer",
        "company": "Uber",
        "description": "Build internal developer platforms that accelerate engineering velocity. Design service meshes, build deployment pipelines, and create self-service infrastructure tools used by thousands of engineers.",
        "requirements": "5+ years platform or infrastructure engineering. Experience building developer tools, CI/CD systems, and service orchestration platforms.",
        "employment_type": "full_time",
        "role_type": "devops",
        "experience_min": 5,
        "experience_max": 9,
        "tech_stack": ["Go", "Kubernetes", "Terraform", "gRPC", "Prometheus", "Cadence"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 4000000,
        "salary_max": 7500000,
        "salary_currency": "INR",
        "apply_url": "https://uber.com/careers",
        "source": "manual",
    },
    {
        "title": "iOS Developer",
        "company": "PhonePe",
        "description": "Build and maintain PhonePe's iOS app used by 400M+ users. Implement payment flows, biometric authentication, and smooth animations. Optimize app size, startup time, and battery usage.",
        "requirements": "3+ years iOS development with Swift. Experience with UIKit/SwiftUI, Core Data, and payment SDK integrations.",
        "employment_type": "full_time",
        "role_type": "mobile",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Swift", "SwiftUI", "UIKit", "Core Data", "Combine", "XCTest"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://phonepe.com/careers",
        "source": "manual",
    },
    {
        "title": "GenAI Engineer",
        "company": "Turing",
        "description": "Build LLM-powered features for developer productivity tools. Design RAG pipelines, fine-tune models, implement prompt engineering frameworks, and build evaluation systems for AI outputs.",
        "requirements": "2+ years experience with LLMs and generative AI. Strong Python skills, familiarity with LangChain/LlamaIndex, and experience deploying AI systems to production.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Python", "LangChain", "OpenAI API", "FastAPI", "Pinecone", "Docker"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 3000000,
        "salary_max": 6000000,
        "salary_currency": "INR",
        "apply_url": "https://turing.com/careers",
        "source": "manual",
    },
    {
        "title": "Senior Full Stack Engineer",
        "company": "Coinbase",
        "description": "Build crypto trading and wallet features for millions of users. Work across React frontends and Go/Node backends. Handle real-time price feeds, order matching, and secure asset management.",
        "requirements": "5+ years full stack experience. Comfort with financial systems, real-time data, and security-critical applications.",
        "employment_type": "full_time",
        "role_type": "fullstack",
        "experience_min": 5,
        "experience_max": 10,
        "tech_stack": ["React", "TypeScript", "Go", "Node.js", "PostgreSQL", "Redis"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 6000000,
        "salary_max": 12000000,
        "salary_currency": "INR",
        "apply_url": "https://coinbase.com/careers",
        "source": "manual",
    },
    {
        "title": "Junior Frontend Developer",
        "company": "Zoho",
        "description": "Join Zoho's product team building business applications. Learn from senior engineers while contributing to real features. Work on form builders, dashboards, and workflow automation UIs.",
        "requirements": "0-2 years experience. Strong HTML/CSS/JavaScript fundamentals. Eagerness to learn and grow. B.Tech in CS or equivalent.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 0,
        "experience_max": 2,
        "tech_stack": ["JavaScript", "HTML", "CSS", "React", "Git"],
        "location": "Chennai",
        "is_remote": False,
        "salary_min": 600000,
        "salary_max": 1200000,
        "salary_currency": "INR",
        "apply_url": "https://zoho.com/careers",
        "source": "manual",
    },
    {
        "title": "Rust Systems Engineer",
        "company": "Cloudflare",
        "description": "Build high-performance edge computing infrastructure in Rust. Work on HTTP proxies, DNS resolvers, and WebAssembly runtimes that serve millions of requests per second globally.",
        "requirements": "3+ years systems programming experience. Proficiency in Rust or C++. Understanding of networking protocols, memory management, and performance optimization.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 3,
        "experience_max": 8,
        "tech_stack": ["Rust", "C++", "Linux", "TCP/IP", "WebAssembly", "Lua"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 5000000,
        "salary_max": 10000000,
        "salary_currency": "INR",
        "apply_url": "https://cloudflare.com/careers",
        "source": "manual",
    },
    {
        "title": "Android Developer",
        "company": "Meesho",
        "description": "Build features for India's largest social commerce app. Optimize for low-end devices and slow networks. Implement offline-first patterns, image optimization, and smooth scrolling for product catalogs.",
        "requirements": "2+ years Android development with Kotlin. Experience with Jetpack Compose, MVVM architecture, and performance optimization for diverse device ecosystem.",
        "employment_type": "full_time",
        "role_type": "mobile",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Kotlin", "Jetpack Compose", "Retrofit", "Room", "Coroutines", "Firebase"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 1800000,
        "salary_max": 3500000,
        "salary_currency": "INR",
        "apply_url": "https://meesho.com/careers",
        "source": "manual",
    },
    {
        "title": "Technical Lead - Backend",
        "company": "Groww",
        "description": "Lead a team of 5-8 engineers building investment platform backend. Make architectural decisions, conduct code reviews, and ensure system reliability for stock trading and mutual fund transactions.",
        "requirements": "7+ years backend experience with 2+ years in a lead role. Strong system design skills, experience with financial systems, and ability to mentor junior engineers.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 7,
        "experience_max": 12,
        "tech_stack": ["Java", "Spring Boot", "Kafka", "PostgreSQL", "Redis", "AWS"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 4000000,
        "salary_max": 7000000,
        "salary_currency": "INR",
        "apply_url": "https://groww.in/careers",
        "source": "manual",
    },
    {
        "title": "Data Scientist",
        "company": "Myntra",
        "description": "Build recommendation models for fashion e-commerce. Work on visual search, size prediction, and personalized styling. Combine computer vision with NLP to understand fashion trends and user preferences.",
        "requirements": "3+ years data science experience. Strong ML fundamentals, experience with recommendation systems or computer vision. Ability to take models from research to production.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["Python", "PyTorch", "TensorFlow", "Spark", "SQL", "MLflow"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://myntra.com/careers",
        "source": "manual",
    },
    {
        "title": "DevSecOps Engineer",
        "company": "Juspay",
        "description": "Integrate security into CI/CD pipelines for payment infrastructure. Build automated vulnerability scanning, secrets management, and compliance monitoring. Ensure PCI-DSS compliance across all services.",
        "requirements": "3+ years DevOps/Security experience. Understanding of container security, SAST/DAST tools, and compliance frameworks.",
        "employment_type": "full_time",
        "role_type": "security",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["Kubernetes", "Terraform", "Vault", "Trivy", "Python", "AWS"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 2500000,
        "salary_max": 4500000,
        "salary_currency": "INR",
        "apply_url": "https://juspay.in/careers",
        "source": "manual",
    },
    {
        "title": "Frontend Engineer - Design Systems",
        "company": "Razorpay",
        "description": "Build and maintain Razorpay's design system used across 20+ products. Create accessible, performant React components. Define API patterns, write documentation, and drive adoption across engineering teams.",
        "requirements": "4+ years frontend experience. Deep understanding of component architecture, accessibility (WCAG), and design tokens. Experience building shared libraries.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["React", "TypeScript", "Storybook", "CSS-in-JS", "Testing Library", "Rollup"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 3000000,
        "salary_max": 5500000,
        "salary_currency": "INR",
        "apply_url": "https://razorpay.com/careers",
        "source": "manual",
    },
    {
        "title": "Embedded Systems Engineer",
        "company": "Ather Energy",
        "description": "Develop firmware for electric vehicle systems. Work on battery management, motor control, and vehicle diagnostics. Write safety-critical code for real-time embedded platforms.",
        "requirements": "3+ years embedded systems experience. Proficiency in C/C++, RTOS concepts, and hardware-software integration. Automotive experience is a plus.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["C", "C++", "RTOS", "CAN Bus", "ARM", "Python"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 1800000,
        "salary_max": 3500000,
        "salary_currency": "INR",
        "apply_url": "https://atherenergy.com/careers",
        "source": "manual",
    },
    {
        "title": "Technical Writer - Developer Docs",
        "company": "Postman",
        "description": "Write clear, developer-friendly API documentation and tutorials. Create code samples, quickstart guides, and conceptual explanations. Work with engineering to document new features and maintain existing docs.",
        "requirements": "2+ years technical writing for developer audiences. Ability to read and write code. Experience with docs-as-code workflows and API documentation tools.",
        "employment_type": "full_time",
        "role_type": "fullstack",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Markdown", "OpenAPI", "JavaScript", "Python", "Git"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 1500000,
        "salary_max": 3000000,
        "salary_currency": "INR",
        "apply_url": "https://postman.com/careers",
        "source": "manual",
    },
    {
        "title": "MLOps Engineer",
        "company": "Walmart Labs",
        "description": "Build ML infrastructure for demand forecasting and supply chain optimization. Design model serving pipelines, feature stores, and experiment tracking systems at Walmart scale.",
        "requirements": "3+ years MLOps or ML infrastructure experience. Strong Python and cloud skills. Experience with model deployment, monitoring, and A/B testing frameworks.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "Kubernetes", "MLflow", "Airflow", "Spark", "GCP"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 3000000,
        "salary_max": 5500000,
        "salary_currency": "INR",
        "apply_url": "https://careers.walmart.com",
        "source": "manual",
    },
    {
        "title": "React Native Developer",
        "company": "Nykaa",
        "description": "Build cross-platform mobile experiences for beauty and fashion e-commerce. Implement product discovery, AR try-on features, and seamless checkout flows. Optimize for performance across iOS and Android.",
        "requirements": "2+ years React Native experience. Understanding of native modules, navigation patterns, and app store deployment processes.",
        "employment_type": "full_time",
        "role_type": "mobile",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["React Native", "TypeScript", "Redux", "Firebase", "CodePush"],
        "location": "Mumbai",
        "is_remote": False,
        "salary_min": 1500000,
        "salary_max": 3000000,
        "salary_currency": "INR",
        "apply_url": "https://nykaa.com/careers",
        "source": "manual",
    },
    {
        "title": "Golang Microservices Developer",
        "company": "Zerodha",
        "description": "Build low-latency trading infrastructure in Go. Design order routing systems, market data processors, and risk management engines. Every millisecond matters in this role.",
        "requirements": "3+ years Go experience. Understanding of financial markets, low-latency systems, and concurrent programming patterns.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Go", "PostgreSQL", "Redis", "NATS", "gRPC", "Linux"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 3000000,
        "salary_max": 6000000,
        "salary_currency": "INR",
        "apply_url": "https://zerodha.com/careers",
        "source": "manual",
    },
    {
        "title": "Full Stack Intern",
        "company": "Cuvette",
        "description": "Work on real-world projects as a full stack intern. Build features using React and Node.js. Get mentorship, code reviews, and hands-on experience shipping production code.",
        "requirements": "Currently pursuing B.Tech or equivalent. Basic knowledge of React and Node.js. Portfolio with at least 2 personal projects.",
        "employment_type": "internship",
        "role_type": "fullstack",
        "experience_min": 0,
        "experience_max": 0,
        "tech_stack": ["React", "Node.js", "MongoDB", "Express", "Git"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 15000,
        "salary_max": 30000,
        "salary_currency": "INR",
        "apply_url": "https://cuvette.tech",
        "source": "manual",
    },
    {
        "title": "Senior Data Engineer",
        "company": "Swiggy",
        "description": "Build real-time data pipelines for delivery optimization. Process millions of events per minute for ETA prediction, demand forecasting, and driver allocation. Design data lake architecture and self-serve analytics tools.",
        "requirements": "5+ years data engineering experience. Expert-level SQL, experience with streaming systems, and ability to design data models for complex business domains.",
        "employment_type": "full_time",
        "role_type": "data",
        "experience_min": 5,
        "experience_max": 9,
        "tech_stack": ["Spark", "Kafka", "Flink", "Python", "Airflow", "AWS", "Hive"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 3500000,
        "salary_max": 6500000,
        "salary_currency": "INR",
        "apply_url": "https://swiggy.com/careers",
        "source": "manual",
    },
    {
        "title": "Freelance UI/UX Developer",
        "company": "Upwork",
        "description": "Take on freelance projects building modern web interfaces. Work with startups and enterprises on landing pages, dashboards, and SaaS products. Set your own rates and schedule.",
        "requirements": "2+ years frontend development. Strong design sense and ability to translate Figma designs to pixel-perfect code. Portfolio required.",
        "employment_type": "freelance",
        "role_type": "frontend",
        "experience_min": 2,
        "experience_max": 10,
        "tech_stack": ["React", "Tailwind CSS", "Figma", "Next.js", "Framer Motion"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 2000000,
        "salary_max": 6000000,
        "salary_currency": "INR",
        "apply_url": "https://upwork.com",
        "source": "manual",
    },
    {
        "title": "Backend Engineer - Node.js",
        "company": "Lenskart",
        "description": "Build e-commerce backend services for eyewear retail. Design inventory management, order processing, and virtual try-on APIs. Handle high traffic during sales events.",
        "requirements": "2+ years Node.js backend experience. Familiarity with MongoDB, caching strategies, and building RESTful APIs at scale.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Node.js", "TypeScript", "MongoDB", "Redis", "RabbitMQ", "AWS"],
        "location": "Gurgaon",
        "is_remote": False,
        "salary_min": 1500000,
        "salary_max": 3000000,
        "salary_currency": "INR",
        "apply_url": "https://lenskart.com/careers",
        "source": "manual",
    },
    {
        "title": "Computer Vision Engineer",
        "company": "Ola",
        "description": "Build perception systems for autonomous driving. Work on object detection, lane tracking, and depth estimation using camera and LiDAR data. Deploy models on edge devices in real-time.",
        "requirements": "3+ years computer vision experience. Strong C++ and Python skills. Experience with deep learning for perception, sensor fusion, and real-time inference.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 3,
        "experience_max": 7,
        "tech_stack": ["Python", "C++", "PyTorch", "OpenCV", "TensorRT", "ROS"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 3000000,
        "salary_max": 6000000,
        "salary_currency": "INR",
        "apply_url": "https://ola.com/careers",
        "source": "manual",
    },
    {
        "title": "Contract DevOps Consultant",
        "company": "TCS",
        "description": "6-month contract to set up cloud infrastructure for a banking client. Migrate on-premise workloads to AWS, implement CI/CD, and train the client's team on cloud-native practices.",
        "requirements": "4+ years DevOps experience. AWS certifications preferred. Experience with enterprise migrations and working with non-technical stakeholders.",
        "employment_type": "contract",
        "role_type": "devops",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["AWS", "Terraform", "Docker", "Jenkins", "Ansible", "Linux"],
        "location": "Mumbai",
        "is_remote": False,
        "salary_min": 150000,
        "salary_max": 300000,
        "salary_currency": "INR",
        "apply_url": "https://tcs.com/careers",
        "source": "manual",
    },
    {
        "title": "Engineering Manager",
        "company": "Flipkart",
        "description": "Lead a team of 10-15 engineers building Flipkart's search and discovery platform. Drive technical strategy, hire and grow engineers, and ensure delivery of high-impact projects.",
        "requirements": "10+ years engineering experience with 3+ years managing teams. Strong system design skills, ability to balance technical debt with feature delivery.",
        "employment_type": "full_time",
        "role_type": "backend",
        "experience_min": 10,
        "experience_max": 16,
        "tech_stack": ["Java", "Elasticsearch", "Kafka", "Kubernetes", "AWS"],
        "location": "Bangalore",
        "is_remote": False,
        "salary_min": 6000000,
        "salary_max": 12000000,
        "salary_currency": "INR",
        "apply_url": "https://flipkart.com/careers",
        "source": "manual",
    },
    {
        "title": "Vue.js Frontend Developer",
        "company": "Freshworks",
        "description": "Build customer support and CRM interfaces using Vue.js. Create real-time chat widgets, ticket management dashboards, and workflow automation UIs. Focus on performance and accessibility.",
        "requirements": "2+ years Vue.js experience. Understanding of state management (Vuex/Pinia), component testing, and building accessible web applications.",
        "employment_type": "full_time",
        "role_type": "frontend",
        "experience_min": 2,
        "experience_max": 5,
        "tech_stack": ["Vue.js", "TypeScript", "Pinia", "Vite", "Cypress", "Tailwind CSS"],
        "location": "Chennai",
        "is_remote": True,
        "salary_min": 1500000,
        "salary_max": 3000000,
        "salary_currency": "INR",
        "apply_url": "https://freshworks.com/careers",
        "source": "manual",
    },
    {
        "title": "Kubernetes Platform Engineer",
        "company": "Nutanix",
        "description": "Build and operate large-scale Kubernetes platforms for enterprise customers. Design multi-tenant clusters, implement GitOps workflows, and build self-healing infrastructure.",
        "requirements": "4+ years Kubernetes experience. CKA/CKAD certified preferred. Experience with cluster operations, networking (CNI), and storage provisioning at scale.",
        "employment_type": "full_time",
        "role_type": "devops",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["Kubernetes", "Go", "Helm", "ArgoCD", "Istio", "Prometheus"],
        "location": "Bangalore",
        "is_remote": True,
        "salary_min": 3000000,
        "salary_max": 5500000,
        "salary_currency": "INR",
        "apply_url": "https://nutanix.com/careers",
        "source": "manual",
    },
    {
        "title": "AI Product Engineer",
        "company": "Sprinklr",
        "description": "Build AI-powered features for enterprise social media management. Implement sentiment analysis, auto-response generation, and content recommendation engines. Bridge product thinking with ML engineering.",
        "requirements": "3+ years building AI-powered products. Full stack capability with ML integration experience. Understanding of NLP and production ML systems.",
        "employment_type": "full_time",
        "role_type": "ml",
        "experience_min": 3,
        "experience_max": 6,
        "tech_stack": ["Python", "React", "FastAPI", "OpenAI API", "PostgreSQL", "Docker"],
        "location": "Gurgaon",
        "is_remote": False,
        "salary_min": 2500000,
        "salary_max": 5000000,
        "salary_currency": "INR",
        "apply_url": "https://sprinklr.com/careers",
        "source": "manual",
    },
    {
        "title": "Database Reliability Engineer",
        "company": "Supabase",
        "description": "Keep PostgreSQL running at scale for thousands of customer databases. Build automated failover, backup systems, and performance monitoring. Contribute to open-source database tooling.",
        "requirements": "4+ years PostgreSQL administration. Deep understanding of replication, query optimization, and database internals. Experience with managed database platforms.",
        "employment_type": "full_time",
        "role_type": "devops",
        "experience_min": 4,
        "experience_max": 8,
        "tech_stack": ["PostgreSQL", "Go", "Linux", "Terraform", "AWS", "Prometheus"],
        "location": "Remote",
        "is_remote": True,
        "salary_min": 5000000,
        "salary_max": 9000000,
        "salary_currency": "INR",
        "apply_url": "https://supabase.com/careers",
        "source": "manual",
    },
]


async def seed():
    print(f"Seeding {len(JOBS)} additional jobs...")
    for i, job in enumerate(JOBS):
        try:
            await create_job(job)
            print(f"  [{i+1}/{len(JOBS)}] Created: {job['title']} at {job['company']}")
        except Exception as e:
            print(f"  [{i+1}/{len(JOBS)}] FAILED: {job['title']} -> {e}")
    print("Done!")


if __name__ == "__main__":
    asyncio.run(seed())
