import { useState, useEffect } from "react";
import { Brain, Search, Target, TrendingUp, Database, Zap } from "lucide-react";
import api from "@/services/api";

export default function AboutPage() {
  const [stats, setStats] = useState({ jobs: 0, skills: 0, remote: 0 });

  useEffect(() => {
    api.get("/api/resumes/trends").then((r) => {
      setStats({
        jobs: r.data.total_jobs || 0,
        skills: Object.keys(r.data.tech_demand || {}).length,
        remote: r.data.remote_percentage || 0,
      });
    }).catch(() => {});
  }, []);

  return (
    <div className="animate-fade-in max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold text-foreground">How Connect+ Works</h1>
      <p className="mt-3 text-muted-foreground">
        Connect+ isn't another job board with keyword filters. It uses AI and vector embeddings
        to understand what you're looking for — and what you're actually qualified for.
      </p>

      {/* Live stats */}
      {stats.jobs > 0 && (
        <div className="mt-8 grid grid-cols-3 gap-4">
          <StatCard value={stats.jobs} label="Jobs indexed" />
          <StatCard value={stats.skills} label="Skills tracked" />
          <StatCard value={`${stats.remote}%`} label="Remote roles" />
        </div>
      )}

      {/* System explanation */}
      <div className="mt-10 space-y-8">
        <SystemSection
          icon={Search}
          title="Semantic Search"
          description="Every job listing is converted into a 1536-dimensional vector embedding using Gemini. When you search, your query is embedded the same way and matched by cosine similarity — not keywords. Searching 'build APIs for payments' finds payment backend roles even if they don't contain those exact words."
        />
        <SystemSection
          icon={Target}
          title="Role Fit Scoring"
          description="Your fit score is a weighted combination of 4 factors: tech stack overlap (40%), experience match (25%), project relevance from GitHub (20%), and competitive programming strength (15%). Each factor is scored 0-100 independently, then combined into your overall fit percentage."
        />
        <SystemSection
          icon={Brain}
          title="Resume Tailoring"
          description="When you tailor your resume for a job, Claude analyzes your resume text against the job's requirements. It identifies strengths, gaps, and gives specific suggestions — not generic advice. Results are cached per job so you don't burn API calls on repeat views."
        />
        <SystemSection
          icon={TrendingUp}
          title="Growth Roadmaps"
          description="Roadmaps are generated by analyzing your profile, GitHub projects, and the skills demanded by your target role across all jobs in the database. The AI identifies gaps and creates a week-by-week learning path with real resources."
        />
        <SystemSection
          icon={Database}
          title="Job Data"
          description="Jobs are synced daily from the Adzuna API across 10 search categories. Each listing gets auto-extracted tech stacks, inferred role types, and vector embeddings for semantic search. The sync is idempotent — duplicates are skipped automatically."
        />
        <SystemSection
          icon={Zap}
          title="GitHub Analysis"
          description="When you connect GitHub, we fetch your repos and their language breakdowns. Detected languages are auto-added to your skills. AI analysis (via Claude) infers tech stacks, generates summaries, and scores each repo's relevance to your target roles."
        />
      </div>

      {/* Tech stack */}
      <div className="mt-12 pt-8 border-t border-border">
        <h2 className="text-lg font-semibold text-foreground">Built With</h2>
        <div className="mt-3 flex flex-wrap gap-2">
          {["React", "TypeScript", "Tailwind CSS", "FastAPI", "Python", "Supabase", "PostgreSQL", "pgvector", "Claude (OpenRouter)", "Gemini Embeddings", "Adzuna API", "Vercel"].map((tech) => (
            <span key={tech} className="rounded-md bg-accent px-3 py-1.5 text-xs font-medium text-accent-foreground">
              {tech}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

function StatCard({ value, label }: { value: number | string; label: string }) {
  return (
    <div className="rounded-xl border border-border bg-card p-4 text-center">
      <p className="text-2xl font-bold text-primary">{value}</p>
      <p className="text-xs text-muted-foreground mt-1">{label}</p>
    </div>
  );
}

function SystemSection({ icon: Icon, title, description }: { icon: any; title: string; description: string }) {
  return (
    <div className="flex gap-4">
      <div className="shrink-0 mt-1">
        <Icon className="h-5 w-5 text-primary" />
      </div>
      <div>
        <h3 className="font-semibold text-foreground">{title}</h3>
        <p className="mt-1 text-sm text-muted-foreground leading-relaxed">{description}</p>
      </div>
    </div>
  );
}
